(function () {
  'use strict';
  var SITE_BASE = '/Miracle-archive/';
  var repoRootHandle = null, assetFolderHandle = null, assetFolderParts = [], nextImageNumber = 1, localPreviewUrls = {};
  function byId(id) { return document.getElementById(id); }
  function status(text, ready) { var node = byId('worldAssetStatus'); node.innerHTML = text; node.classList.toggle('repo-ready', !!ready); }
  function extensionOf(file) { var match = String(file.name || '').toLowerCase().match(/\.(png|jpe?g|gif|webp|avif|svg|bmp)$/); if (match) return '.' + match[1]; var types = {'image/png':'.png','image/jpeg':'.jpg','image/gif':'.gif','image/webp':'.webp','image/avif':'.avif','image/svg+xml':'.svg','image/bmp':'.bmp'}; return types[file.type] || '.png'; }
  function folderWebBase() { return SITE_BASE + assetFolderParts.join('/') + '/'; }
  function numberedName(file) { var name = String(nextImageNumber).padStart(2, '0') + extensionOf(file); nextImageNumber += 1; return name; }
  async function scanNextNumber() { var max = 0; for await (var entry of assetFolderHandle.values()) { if (entry.kind !== 'file') continue; var match = entry.name.match(/^(\d+)\.[^.]+$/); if (match) max = Math.max(max, Number(match[1])); } nextImageNumber = max + 1; }
  async function copyIntoFolder(file, name) { var target = await assetFolderHandle.getFileHandle(name, {create:true}), writable = await target.createWritable(); await writable.write(file); await writable.close(); }
  function remember(path, file) { if (localPreviewUrls[path]) URL.revokeObjectURL(localPreviewUrls[path]); localPreviewUrls[path] = URL.createObjectURL(file); applyPreviews(); }
  function applyPreviews() { var preview = byId('previewStage'); if (!preview) return; preview.querySelectorAll('img').forEach(function (image) { var path = image.dataset.repoPath || image.getAttribute('src'); if (!localPreviewUrls[path]) return; image.dataset.repoPath = path; image.src = localPreviewUrls[path]; }); }
  function setPath(input, path) { input.value = path; input.dispatchEvent(new Event('input', {bubbles:true})); }
  async function useAsset(file, input, existingPath) { if (!file) return; if (!assetFolderHandle) { status('먼저 <strong>이미지 저장 폴더 연결</strong>을 눌러 <code>assets/world/...</code> 폴더를 연결하세요.', false); return; } var name = existingPath ? '' : numberedName(file), path = existingPath || folderWebBase() + name; remember(path, file); setPath(input, path); try { if (!existingPath) await copyIntoFolder(file, name); status(existingPath ? '기존 이미지를 불러왔습니다: <code>' + path + '</code>' : '이미지를 <strong>' + name + '</strong>으로 저장했습니다: <code>' + path + '</code>', true); } catch (error) { status('경로는 입력했지만 이미지 저장에 실패했습니다: ' + error.message, false); } }
  function normalize(input) { var value = input.value.trim().replace(/[\\₩]+/g, '/'); if (!value) return; var index = value.toLowerCase().indexOf('/assets/'); if (index >= 0) value = value.slice(index + 1); if (value.toLowerCase().indexOf('assets/') === 0) setPath(input, SITE_BASE + value.replace(/^\/+/, '').replace(/\/{2,}/g, '/')); }
  function picker(id, text, input) { var label = document.createElement('label'); label.className = 'world-asset-pick'; label.innerHTML = '<input id="' + id + '" type="file" accept="image/*"><span>' + text + '</span>'; var fileInput = label.querySelector('input'); fileInput.addEventListener('change', function () { useAsset(this.files[0], input, ''); this.value = ''; }); label.querySelector('span').addEventListener('click', async function (event) { if (!assetFolderHandle || !window.showOpenFilePicker || !assetFolderHandle.resolve) return; event.preventDefault(); try { var handles = await window.showOpenFilePicker({startIn:assetFolderHandle,multiple:false,types:[{description:'Images',accept:{'image/*':['.png','.jpg','.jpeg','.gif','.webp','.avif','.svg','.bmp']}}]}), handle = handles[0], parts = await assetFolderHandle.resolve(handle), existingPath = parts && parts.length ? folderWebBase() + parts.join('/') : ''; useAsset(await handle.getFile(), input, existingPath); } catch (error) { if (error.name !== 'AbortError') status(error.message, false); } }); input.insertAdjacentElement('afterend', label); input.addEventListener('change', function () { normalize(input); }); input.addEventListener('blur', function () { normalize(input); }); }
  var style = document.createElement('style'); style.textContent = '.world-asset-pick{display:inline-flex;margin-top:4px;overflow:hidden;position:relative}.world-asset-pick input{height:1px;opacity:0;position:absolute;width:1px}.world-asset-pick span{background:#fff;border:1px solid #cbc7ce;border-radius:4px;color:#68636c;cursor:pointer;font-size:.59rem;font-weight:750;padding:6px 8px}.repo-ready{color:#4f765c!important}'; document.head.appendChild(style);
  byId('connectWorldAssets').addEventListener('click', async function () { if (!window.showDirectoryPicker) { status('이 브라우저는 폴더 연결을 지원하지 않습니다. Chrome 또는 Edge를 사용하세요.', false); return; } try { status('먼저 <strong>Miracle-archive</strong> 저장소 폴더를 선택하세요.', false); repoRootHandle = await window.showDirectoryPicker({id:'Miracle-world-repo-root',mode:'readwrite'}); window.alert('이제 assets/world 안에서 이미지를 저장할 폴더를 선택하세요. 새 폴더를 만들어 선택해도 됩니다.'); assetFolderHandle = await window.showDirectoryPicker({id:'Miracle-world-assets',mode:'readwrite',startIn:repoRootHandle}); assetFolderParts = await repoRootHandle.resolve(assetFolderHandle); if (!assetFolderParts || assetFolderParts.length < 2 || assetFolderParts[0].toLowerCase() !== 'assets' || assetFolderParts[1].toLowerCase() !== 'world') { assetFolderHandle = null; assetFolderParts = []; throw new Error('두 번째 단계에서는 선택한 저장소의 assets/world 안에 있는 폴더를 선택하세요.'); } await scanNextNumber(); status('연결 완료: <code>' + assetFolderParts.join('/') + '/</code> · 다음 새 이미지는 <strong>' + String(nextImageNumber).padStart(2, '0') + '</strong>번으로 저장됩니다.', true); } catch (error) { if (error.name !== 'AbortError') status(error.message, false); } });
  picker('portalHeroFile', '대표 이미지 선택', byId('pHero'));
  picker('auCoverFile', 'AU 커버 선택', byId('aCover'));
  picker('subjectDFile', 'D 이미지 선택', byId('aDImage'));
  picker('subjectKFile', 'K 이미지 선택', byId('aKImage'));
  new MutationObserver(applyPreviews).observe(byId('previewStage'), {childList:true,subtree:true});
})();

